codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 65...85
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude # don't send status checks that don't have flag coverage uploaded
      only_pulls: true
    project:
      default: off
      valctx:
        target: auto
        threshold: 1%
        flags:
          - valctx
    patch: off

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

flags:
  valctx:
    paths:
      - valctx/
