name: codeconv
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codeconv:
    name: "Test Coverage"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Generate coverage report"
        run: make test-coverage
      - name: Upload coverage reports base62 to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./base62.txt
          flags: base62
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage reports valctx to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./valctx.txt
          flags: valctx
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
